version: '3.8'

services:
  
  db-mysql:
    image: mysql:8.0 
    container_name: fab-mysql-db
    environment:
      
      MYSQL_ROOT_PASSWORD: Mysql123
      MYSQL_DATABASE: fab_db 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

 
  app-fab:
    build: . 
    container_name: fab-spring-app
    ports:
      - "8080:8080" 
    depends_on:
      - db-mysql 
    environment:
    
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/fab_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sua_senha_segura
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data: 